kind: Service
apiVersion: v1
metadata:
    name: haproxy-service
spec:
    selector:
        app: haproxy
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
    type: NodePort